Vagrant.configure("2") do |config|
  config.vm.define "nodo1" do |l1|
    l1.vm.box = "bento/ubuntu-16.04"
    l1.vm.hostname = "nodo1"
    l1.vm.network :private_network, ip: "192.168.33.11"
    l1.vm.provider "virtualbox" do |vb1|
      vb1.name = "nodo1"
      vb1.memory = "512"
      vb1.cpus = "1"
    end
   
  end
  config.vm.define "nodo2" do |l2|
    l2.vm.box = "bento/ubuntu-16.04"
    l2.vm.hostname = "nodo2"
    l2.vm.network :private_network, ip: "192.168.33.12"
    l2.vm.provider "virtualbox" do |vb2|
      vb2.name = "nodo2"
      vb2.memory = "512"
      vb2.cpus = "1"
    end
   
  end
end