---
- hosts: server-lbs
  remote_user: root
  tasks:


    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Install OpenJDK Java
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        openjdk-8-jdk

    - name: Add the Jenkins public GPG key to the apt repo
      apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
      become: true
    
    - name: Add Jenkins apt repo to the trusted sources list
      apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/'
                      update_cache={{ update_apt_cache }}
                      state=present

    - name: Install Jenkins server
      apt: name=jenkins state=present


