Vagrant.configure("2") do |config|
  config.vm.define "Master" do |l1|
    l1.vm.box = "bento/ubuntu-16.04"
    l1.vm.hostname = "Master"
    l1.vm.network :private_network, ip: "192.168.33.10"
    l1.vm.synced_folder "shared","/home/vagrant/projects"
    l1.vm.provision "shell", path: "config_ansible.sh"
    l1.vm.provider "virtualbox" do |vb1|
      vb1.name = "Master"
      vb1.memory = "512"
      vb1.cpus = "1"
    end
   
  end
 
    
  end
  